//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericRepositoryCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenericRepositoryCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///CREATE FUNCTION Initcap (@Str varchar(max))
        ///RETURNS varchar(max) AS
        ///BEGIN
        ///  DECLARE @Result varchar(2000)
        ///  SET @Str = LOWER(@Str) + &apos; &apos;
        ///  SET @Result = &apos;&apos;
        ///  WHILE 1=1
        ///  BEGIN
        ///    IF PATINDEX(&apos;% %&apos;,@Str) = 0 BREAK
        ///    SET @Result = @Result + UPPER(Left(@Str,1))+
        ///    SubString  (@Str,2,CharIndex(&apos; &apos;,@Str)-1)
        ///    SET @Str = SubString(@Str,
        ///      CharIndex(&apos; &apos;,@Str)+1,Len(@Str))
        ///  END
        ///  SET @Result = Left(@Result,Len(@Result))
        ///  RETURN @Result
        ///END 
        ///
        ///GO
        ///
        ///create function ConvertDataType(@ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Proc_mssql_classgenerator {
            get {
                return ResourceManager.GetString("Proc_mssql_classgenerator", resourceCulture);
            }
        }
    }
}
